language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
env:
  - DJANGO="django>=1.11,<2.0"
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"
install:
  - pip install $DJANGO
  - pip install requests
  - python setup.py -q install
script: python runtests.py
notifications:
  email: false
