language: python
python:
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
install:
  - pip install $DJANGO
  - pip install requests
  - python setup.py -q install
script: python runtests.py
notifications:
  email: false
